chore: Dockerizzazione server
teamdigitale/dataviz-srv pull request #2
Opened 2024-09-10 09:03 UTC by valeriocomo

Dockerizzazione server

2024-09-12 14:54 UTC, tensor5 requested changes

2024-09-12 14:54 UTC, tensor5 commented on Dockerfile
> +RUN curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n \
Non sarebbe più facile installare il pacchetto node della di ubuntu tramite apt?

2024-09-12 14:54 UTC, tensor5 commented on Dockerfile
> +COPY package.json bun.lockb /temp/prod/
Si può usare WORKDIR /temp/prod

2024-09-12 14:57 UTC, valeriocomo commented on Dockerfile
> +COPY package.json bun.lockb /temp/prod/
solo per questo stage?

2024-09-12 15:35 UTC, valeriocomo commented on Dockerfile
> +RUN curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n \
In teoria si, in pratica no. La versione di nodejs offerta da apt è obsoleta.
Le soluzioni alternative erano due:

aggiungere i PPA repo di node
utilizzare un node version mananger.
Ho scelto la seconda perchè, anche se più macchinosa, la ritengo più robusta.
Per altre info, questo blog post dettaglia minuziosamente il ventaglio di soluzioni.

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-22-04

2024-09-13 10:19 UTC, tensor5 requested changes

2024-09-13 10:19 UTC, tensor5 commented on Dockerfile
> +COPY package.json bun.lockb /temp/prod/
In questo stage perché eviterebbe la parte di script `RUN mkdir ...` e `RUN cd ... &&`.

2024-09-13 10:19 UTC, tensor5 commented on Dockerfile
> +RUN mkdir -p /temp/prod
`mkdir` non è più necessario.

2024-09-13 12:47 UTC, valeriocomo commented on Dockerfile
> +RUN mkdir -p /temp/prod
rimuovo

2024-09-13 12:50 UTC, valeriocomo commented on Dockerfile
> +COPY package.json bun.lockb /temp/prod/
comandi rimossi

2024-09-13 13:13 UTC, tensor5 approved these changes

2024-09-13 13:15 UTC, merged